---
name: "Test"

on:
    pull_request: {}
    push:
        branches:
            - "master"

env:
    CI: true

jobs:
    test:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@v1"

            - name: "Use Node.js 12.x"
              uses: "actions/setup-node@v1"
              with:
                  node-version: "12.x"

            - name: "Install"
              run: "yarn install --no-audit"

            - name: "Verify"
              run: "yarn test"
