---
name: "Test"

on:
    pull_request: {}
    push:
        branches:
            - "master"

env:
    CI: true

jobs:
    test:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@v1"

            - name: "Use Node.js 12.x"
              uses: "actions/setup-node@v1"
              with:
                  node-version: "12.x"

            - uses: "shivammathur/setup-php@master"
              with:
                  php-version: "7.4"
                  coverage: "xdebug"

            - name: "Install"
              run: "yarn install --no-audit && composer install"

            - name: "Verify"
              run: "yarn test && composer test"
